//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitySailor
{
    [Serializable]
    public class SetUnitySailAngleMsg : Message
    {
        public const string k_RosMessageName = "unity_sailor_msgs/SetUnitySailAngle";
        public override string RosMessageName => k_RosMessageName;

        public float sail_angle;

        public SetUnitySailAngleMsg()
        {
            this.sail_angle = 0.0f;
        }

        public SetUnitySailAngleMsg(float sail_angle)
        {
            this.sail_angle = sail_angle;
        }

        public static SetUnitySailAngleMsg Deserialize(MessageDeserializer deserializer) => new SetUnitySailAngleMsg(deserializer);

        private SetUnitySailAngleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sail_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sail_angle);
        }

        public override string ToString()
        {
            return "SetUnitySailAngleMsg: " +
            "\nsail_angle: " + sail_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
