//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitySailor
{
    [Serializable]
    public class UnityRudderTwistMsg : Message
    {
        public const string k_RosMessageName = "unity_sailor_msgs/UnityRudderTwist";
        public override string RosMessageName => k_RosMessageName;

        public int twist;

        public UnityRudderTwistMsg()
        {
            this.twist = 0;
        }

        public UnityRudderTwistMsg(int twist)
        {
            this.twist = twist;
        }

        public static UnityRudderTwistMsg Deserialize(MessageDeserializer deserializer) => new UnityRudderTwistMsg(deserializer);

        private UnityRudderTwistMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.twist);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "UnityRudderTwistMsg: " +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
