//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitySailor
{
    [Serializable]
    public class UnityBoatTrimMsg : Message
    {
        public const string k_RosMessageName = "unity_sailor_msgs/UnityBoatTrim";
        public override string RosMessageName => k_RosMessageName;

        public float rig_rotation;
        public float rudder_rotation;

        public UnityBoatTrimMsg()
        {
            this.rig_rotation = 0.0f;
            this.rudder_rotation = 0.0f;
        }

        public UnityBoatTrimMsg(float rig_rotation, float rudder_rotation)
        {
            this.rig_rotation = rig_rotation;
            this.rudder_rotation = rudder_rotation;
        }

        public static UnityBoatTrimMsg Deserialize(MessageDeserializer deserializer) => new UnityBoatTrimMsg(deserializer);

        private UnityBoatTrimMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rig_rotation);
            deserializer.Read(out this.rudder_rotation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rig_rotation);
            serializer.Write(this.rudder_rotation);
        }

        public override string ToString()
        {
            return "UnityBoatTrimMsg: " +
            "\nrig_rotation: " + rig_rotation.ToString() +
            "\nrudder_rotation: " + rudder_rotation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
